### ISSUE TITLE
Importing the data

### ISSUE THREAD

**Issue by vinamrak** [ACM-VIT/Shakespeare-Translate#8]
**Function to edit in main.py for this issue**:
def importData( )

The purpose of this issue is to import the data into main.ipynb  

The link to the dataset has been provided in the dataset section already. You can find all the Shakespearean novels there.

Each novel is represented by two text files:

1)The files named "original" contain the novels in original Shakespearean format line by line.
2)The same novel with name "modern" contains the whole novel in modern english format.

In this way, the same line in a novel can be extracted in Shakespearean format from the "original" file and in modern format from the "modern" file.

**Comment by Avantikaa** [comment]
Hi @vinamrak Interesting project! I would like to start and contribute. I have done a few projects on NLP before Can you please assign this to me?

**Comment by vinamrak** [comment]
> Hi @vinamrak Interesting project! I would like to start and contribute. I have done a few projects on NLP before Can you please assign this to me?

You have been assigned. Good luck!

PS: Although we won't be able to merge your PRs for issues other than the one you have been assigned, you are more than welcome to submit PRs to complete other parts of the projects or the whole project itself.

**Comment by vinamrak** [comment]
Good job @Avantikaa your PR has been merged!
