### ISSUE TITLE
Import packages and preprocess the data

### ISSUE THREAD

**Issue by vinamrak** [ACM-VIT/Shakespeare-Translate#9]
**All the functions mentioned in this issue must be solved for this issue to be solved completely.**

The basic required packages have been given in requirements.txt which can be installed using the pip command given in the usage section.

Import the packages in the "Import Packages" section in main.ipynb

Clean and preprocess the data after importing the data and the required packages. 

Within preprocessing, the following steps must be covered:
**1)Convert all the text to lowercase.**

Function to edit in main.ipynb:
def toLowerCase(corpus)

**2)Tokenize the text into a list of sentences.**

Function to edit in main.ipynb:
def sentence_tokenize(corpus)

**3)Tokenize a sentence into a bag of words.**

Function to edit in main.ipynb:
def word_tokenize(sentence):

**4)Convert a sentence into an equivalent list of characters without punctuation(.,?,!)**

Function to edit in main.ipynb:
def listOfAlphabets(sentence):

**Comment by daviddavo** [comment]
Can I be assigned to this issue?

**Comment by vinamrak** [comment]
> Can I be assigned to this issue?

You have been assigned to this issue. Good luck!

PS: Although we won't be able to merge your PRs for issues other than the one you have been assigned, you are more than welcome to submit PRs to complete other parts of the projects or the whole project itself.
